name: Inspections

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up NodeJS
        shell: bash -l {0}
        run: nvm install
      - name: Set up NPM
        run: npm ci
      - name: Build
        run: npm run build